### ISSUE TITLE
Power level inconsistency with Mekanism energy cubes or energy cables

### ISSUE THREAD

**Issue by iExalt** [iopleke/Minechem#794]
When powering the Decomposer or Synthesizer with a Mekanism energy cube or power cables, the energy shown in the machine tooltip is incorrect. The energy shown rises 100 RF only when you exit out of the machine GUI and enter it again. Staring at either the GUI or the machine in the world for any amount of time does not raise the "power level" shown. The tooltip also shows that the machine is unpowered, even though it clearly is powered because I can decompose or synthesize in the machine.

[This album should help illustrate my point](http://imgur.com/a/nsjKs)

The energy cubes and cables used are much more than capable of transferring 100 RF every time I look at the machine. If a TE energy cube is used with Mekanism cables or a Mekanism energy cube is used with TE cables, the same result occurs. Only when using a TE cube directly adjacent to a machine or a TE cube paired with TE cables does the expected result happen: smooth (albeit much slower than the Resonant Energy Cell can output-another bug?) power gain shown in the machine tooltip.

Tested with:
Minecraft 1.7.10
CodeChickenCore-1.0.4.29
CoFHCore-3.0.3-303
Mekanism-8.1.7.252
MekanismTools-8.1.7.252
MekanismGenerators-8.1.7.252
Minechem(latest build from Jenkins)5.0.5.406
NEI-1.0.3.74
ThermalDynamics-1.1.0-161
ThermalExpansion-4.0.2B3-216
ThermalFoundation-1.2.0-102

Thanks to hilburn for reminding me to do this

**Comment by Ipiano** [comment]
It seems like, in general, there's a cap on how much power the machines can accept per/tick. I've got them connected to cryo-stabilized flux ducts that get energy from an induction matrix with a max output of like 40kRF/t, but the fusion core and fission core only seem to accept 100RF/tick

**Comment by Ipiano** [comment]
Just checked, RF input per tick is in the config file
