### ISSUE TITLE
1.7.10 Crash during world generation

### ISSUE THREAD

**Issue by Migmag789** [iopleke/Minechem#844]
WHY... WHYYYYY ???
[crash-2017-06-30_17.24.09-client.txt](https://github.com/iopleke/Minechem/files/1115717/crash-2017-06-30_17.24.09-client.txt)

**Comment by jakimfett** [comment]
Please read the [Bug Contribution Guidelines](https://github.com/iopleke/Minechem/blob/1.7.10-v6/CONTRIBUTING.md).
